CREATE DATABASE dbElectrodomesticos;

USE dbElectrodomesticos;

CREATE TABLE CLIENTE
(
    CODCLI char(4), 
    NOMCLI varchar(60),
    APECLI varchar(80),
    EMACLI varchar(80),
    CELCLI char(9),
    DIRCLI varchar(70),
    ESTCLI char(1),
    CONSTRAINT CODCLI_PK PRIMARY KEY (CODCLI)
);

CREATE TABLE VENDEDOR
(
    CODVEND char(4),
    NOMVEND varchar(60),
    APEVEND varchar(80),
    EMAVEND varchar(80),
    CELVEND char(9),
    DIRVEND varchar(70),
    ESTVEND char(1),
	CONSTRAINT CODVEND_PK PRIMARY KEY (CODVEND)
);

CREATE TABLE PRODUCTO
(
    CODPRO char(5),
    DESCPRO varchar(80),
    CATPRO char(2),
    PREPRO decimal(8.2),
    STOCKPRO int,
    ESTPRO char(1),
    CONSTRAINT CODPRO_PK PRIMARY KEY (CODPRO)
);

CREATE TABLE PROVEEDOR
(
    CODPROV char(5),
    RAZSOCPROV varchar(80),
    RUCPROV varchar(11),
    EMAPROV varchar(70),
    ESTPROV char(1),
    CONSTRAINT CODPROV_PK PRIMARY KEY (CODPROV)
);


CREATE TABLE VENTADETALLE (
    IDVENDET INTEGER,
    CODVEN CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INTEGER,
    PRIMARY KEY (IDVENDET)
);

CREATE TABLE COMPRA(
    CODCOM CHAR(5),
    FECCOM DATETIME,
    CODVEND CHAR(4),
    CODPROV CHAR(5),
    ESTCOM CHAR(1),
    PRIMARY KEY (CODCOM)
);

CREATE TABLE COMPRADETALLE (
    IDCOMDET INTEGER,
    CODCOM CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INTEGER,
    PRIMARY KEY (IDCOMDET)
);

-- Relaciones
ALTER TABLE VENTA
ADD CONSTRAINT CODCLI_FK
FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI);

ALTER TABLE VENTA
ADD CONSTRAINT CODVEND_FK
FOREIGN KEY (CODVEND) REFERENCES VENDEDOR (CODVEND);

ALTER TABLE VENTADETALLE
ADD CONSTRAINT CODVEN_FK
FOREIGN KEY (CODVEN) REFERENCES VENTA (CODVEN);

ALTER TABLE VENTADETALLE
ADD CONSTRAINT CODPRO_FK
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO);

ALTER TABLE COMPRADETALLE
ADD CONSTRAINT CODPROD_FK
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO);

ALTER TABLE COMPRADETALLE
ADD CONSTRAINT CODCOM_FK
FOREIGN KEY (CODCOM) REFERENCES COMPRA (CODCOM);

ALTER TABLE COMPRA
ADD CONSTRAINT CODPROV_FK
FOREIGN KEY (CODPROV) REFERENCES PROVEEDOR (CODPROV);

ALTER TABLE COMPRA
ADD CONSTRAINT CODVENDE_FK
FOREIGN KEY (CODVEND) REFERENCES VENDEDOR (CODVEND);